#### 1. Импортируйте пакет numpy под именем `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Создайте нулевой вектор размера 10 (★☆☆)

In [ ]:
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Как узнать объем памяти любого массива (★☆☆)

In [ ]:
array = np.zeros(10)
print(array.nbytes, 'bytes')
print(array.size * array.itemsize, 'bytes')

80 bytes
80 bytes


#### 4. Создайте вектор со значениями от 10 до 49. (★☆☆)

In [ ]:
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Создайте обратный вектор из вектора в задании 4 (первый элемент становится последним) (★☆☆)

In [ ]:
array = array[::-1]
print(array)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6. Создайте матрицу 3x3 со значениями от 0 до 8. (★☆☆)

In [ ]:
array = np.arange(9).reshape(3, 3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Найти индексы ненулевых элементов из [1,2,0,0,4,0 (★☆☆)

In [ ]:
array = np.nonzero([1,2,0,0,4,0])[0]
print(array)

[0 1 4]


#### 8. Создайте массив 3x3x3 со случайными значениями (★☆☆)

In [ ]:
array = np.random.random(size = (3, 3, 3))
print(array)

[[[0.58912737 0.64824729 0.98672403]
  [0.24594435 0.47465313 0.17349255]
  [0.62512233 0.40187626 0.89585075]]

 [[0.70933728 0.62610579 0.10165001]
  [0.39317196 0.73762164 0.83741568]
  [0.58289302 0.83831752 0.33719429]]

 [[0.61017082 0.80848138 0.34802776]
  [0.69629259 0.66397466 0.85007348]
  [0.36025484 0.58569541 0.84156575]]]


#### 9. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения. (★☆☆)

In [ ]:
array = np.random.random(size = (10, 10))
print(array)
print('Максимальное значение = ', array.max())
print('Минимальное значение = ', array.min())

[[0.09628736 0.92446429 0.45365748 0.71394756 0.50385109 0.07810973
  0.69768172 0.46009375 0.76821473 0.91026441]
 [0.71627683 0.7274344  0.05426412 0.73664205 0.09970687 0.84944398
  0.84425557 0.79510924 0.42910365 0.14542776]
 [0.38264678 0.7115516  0.54839931 0.11098249 0.42932283 0.82326897
  0.24583665 0.65935006 0.23775235 0.36008382]
 [0.588781   0.26400072 0.74048984 0.90274913 0.48712804 0.5773892
  0.27487597 0.06003179 0.1448541  0.78470217]
 [0.26903464 0.09174923 0.65149671 0.05170892 0.35730858 0.15146664
  0.33080337 0.36242185 0.40292253 0.93335365]
 [0.72197569 0.57702702 0.38031429 0.92757544 0.51833951 0.7955696
  0.94233073 0.94370975 0.39798979 0.07817652]
 [0.67608554 0.69361451 0.90432949 0.36969081 0.45561924 0.80912377
  0.7537849  0.09137255 0.53679253 0.92480932]
 [0.52736617 0.29905171 0.16524529 0.63706622 0.71539596 0.93276183
  0.99268793 0.7390227  0.83040971 0.53571123]
 [0.05714166 0.05022289 0.31313473 0.13687869 0.45001513 0.80909116
  0.2402731  0

#### 10. Создайте случайный вектор размера 30 и найдите среднее значение(★☆☆)

In [ ]:
array = np.random.random(30)
print(array)
print('Среднее значение =', array.mean())

[0.41451373 0.19943925 0.09325503 0.41517037 0.87119106 0.98090895
 0.22350428 0.13024974 0.53391001 0.35690372 0.50066959 0.68877901
 0.22075491 0.55694685 0.76307318 0.77489977 0.32876379 0.94294306
 0.60175706 0.28185068 0.53790551 0.91515814 0.26945869 0.97784341
 0.44551146 0.0700943  0.25661506 0.67470253 0.71408733 0.37175833]
Среднее значение = 0.5037539597793718


#### 11. Создайте массив 2d 2x3 c 1 на границе и 0 внутри (★☆☆)

In [ ]:
array = np.ones((2, 3))
array[:, 1] = 0
print(array)

[[1. 0. 1.]
 [1. 0. 1.]]


In [ ]:
array = np.ones((3, 3))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 12. Каков результат следующего выражения? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 13. Рассмотрим массив размера (6,7,8). Каков индекс (x,y,z) 100-го элемента? (★☆☆)

In [ ]:
array = np.arange(1, 337).reshape(6, 7, 8)
point = np.where(array == 100)
print([point[i][0] for i in range(3)])

[1, 5, 3]


#### 14. Умножить матрицу 5x3 на матрицу 3x2(★☆☆)

In [ ]:
matrix_1 = np.random.random(size = (5,3))
matrix_2 = np.random.random(size = (3,2))
print(np.dot(matrix_1, matrix_2))

[[0.3746456  0.12391595]
 [1.17146119 0.34585107]
 [1.85143398 0.547735  ]
 [1.24267206 0.27136186]
 [0.59523585 0.08407159]]


#### 15. Создайте одномерный массив со случайными значениями от 1 до 10, инвертируйте (поменяйте местами) все элементы, со значениями 3 и 8. (★☆☆)

In [ ]:
array = np.random.randint(1, 10, size = 30)
print(array)
number_3, number_8 = np.where(array == 3)[0], np.where(array == 8)[0]
array[number_3], array[number_8] = 8, 3
print(array)

[4 7 5 8 1 8 1 8 4 8 6 4 6 4 5 5 2 7 1 2 6 7 3 3 1 5 5 2 1 6]


array([4, 7, 5, 3, 1, 3, 1, 3, 4, 3, 6, 4, 6, 4, 5, 5, 2, 7, 1, 2, 6, 7,
       8, 8, 1, 5, 5, 2, 1, 6])

#### 16. Каков результат следующих выражений? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-37-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-37-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-37-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 17. Как найти общие значения между двумя массивами? (★☆☆)

In [ ]:
array_1 = np.random.randint(10, size = 10)
print(array_1)
array_2 = np.random.randint(10, size = 10)
print(array_2)
print(np.intersect1d(array_1, array_2))

[0 8 5 6 6 6 9 9 5 4]
[5 8 7 6 3 6 7 7 0 1]
[0 5 6 8]


#### 18. Как вычислить ((A+B)*(-A/2)) с заменой массива А (без копирования)? (★★☆)

In [ ]:
A = np.random.random(size = (3, 3))
print(A)
B = np.arange(3)
print(B)
np.multiply((A + B), (-A / 2), out = A)
print(A)

[[0.80307069 0.56385984 0.5953065 ]
 [0.45644085 0.45023117 0.0570484 ]
 [0.4966681  0.60824128 0.28205385]]
[0 1 2]
[[-0.32246126 -0.44089888 -0.77250142]
 [-0.10416912 -0.32646963 -0.05867566]
 [-0.1233396  -0.48909937 -0.32183104]]


#### 19. Создайте матрицу 5x5 со значениями строк от 0 до 4. (★★☆)

In [ ]:
array = np.zeros((5, 5))
array += np.arange(5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 20. Создайте вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0 (★★☆)

In [ ]:
array = np.linspace(0, 1, 12)[1:-1]
print(array)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 21. Создайте случайный вектор размера 10 и отсортируйте его (★★☆)

In [ ]:
array = np.random.random(10)
array = np.sort(array)
print(array)

[0.13249503 0.16304753 0.1794845  0.23608399 0.4722502  0.49543991
 0.4963543  0.69960218 0.73467537 0.93423491]


#### 22. Можно ли суммировать небольшой массив быстрее, чем np.sum? (★★☆)

In [ ]:
array = np.arange(4)
%timeit sum(array)
%timeit np.sum(array)
%timeit np.add.reduce(array)

1.46 µs ± 287 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
3.35 µs ± 86 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.5 µs ± 263 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 23. Рассмотрим два случайных массива A и B, проверьте, равны ли они(★★☆)

In [ ]:
array_1 = np.random.randint(10, size = 10)
print(array_1)
array_2 = np.random.randint(10, size = 10)
print(array_2)
print(np.allclose(array_1, array_2))

[8 1 5 7 9 1 1 8 5 5]
[6 9 0 2 2 9 2 4 0 5]
False


#### 24. Создайте случайный вектор размера 10 и замените максимальное значение на 0 (★★☆)

In [ ]:
array = np.random.random(10)
print(array)
array[array.argmax()] = 0
print(array)

[0.44145212 0.0555041  0.06165684 0.2342709  0.13611061 0.77933608
 0.90094517 0.67117972 0.27323978 0.82173068]
6
[0.44145212 0.0555041  0.06165684 0.2342709  0.13611061 0.77933608
 0.         0.67117972 0.27323978 0.82173068]


#### 25. Распечатайте минимальное и максимальное представимое значение для каждого скалярного типа numpy (★★☆)

In [ ]:
np.ScalarType

(int,
 float,
 complex,
 bool,
 bytes,
 str,
 memoryview,
 numpy.bool_,
 numpy.complex64,
 numpy.complex128,
 numpy.clongdouble,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 numpy.longdouble,
 numpy.int8,
 numpy.int16,
 numpy.int32,
 numpy.longlong,
 numpy.int64,
 numpy.timedelta64,
 numpy.datetime64,
 numpy.object_,
 numpy.bytes_,
 numpy.str_,
 numpy.uint8,
 numpy.uint16,
 numpy.uint32,
 numpy.ulonglong,
 numpy.uint64,
 numpy.void)

In [ ]:
for dtype in [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64,  np.longlong]:
  print(dtype)
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.complex64, np.complex128, np.float16, np.float32, np.float64, np.longdouble, np.clongdouble]:
  print(dtype)
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)

<class 'numpy.int8'>
-128
127
<class 'numpy.int16'>
-32768
32767
<class 'numpy.int32'>
-2147483648
2147483647
<class 'numpy.int64'>
-9223372036854775808
9223372036854775807
<class 'numpy.uint8'>
0
255
<class 'numpy.uint16'>
0
65535
<class 'numpy.uint32'>
0
4294967295
<class 'numpy.uint64'>
0
18446744073709551615
<class 'numpy.longlong'>
-9223372036854775808
9223372036854775807
<class 'numpy.complex64'>
-3.4028235e+38
3.4028235e+38
<class 'numpy.complex128'>
-1.7976931348623157e+308
1.7976931348623157e+308
<class 'numpy.float16'>
-65500.0
65500.0
<class 'numpy.float32'>
-3.4028235e+38
3.4028235e+38
<class 'numpy.float64'>
-1.7976931348623157e+308
1.7976931348623157e+308
<class 'numpy.longdouble'>
-1.189731495357231765e+4932
1.189731495357231765e+4932
<class 'numpy.clongdouble'>
-1.189731495357231765e+4932
1.189731495357231765e+4932


#### 26. Как вывести все значения большого массива? (★★☆)

In [ ]:
np.set_printoptions(threshold=np.inf)
print(np.arange(1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

#### 27. Рассмотрим случайный вектор формы (100,2), представляющий координаты, найдите расстояния между точками. (★★☆)

In [ ]:
Z = np.random.random((10, 2))
X, Y = np.atleast_2d(Z[:, 0], Z[:, 1])
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
print(D)

[[0.         0.80249391 0.28512899 ... 0.56173429 0.60637964 0.62658519]
 [0.80249391 0.         0.98999134 ... 0.46738715 0.3658476  0.42282658]
 [0.28512899 0.98999134 0.         ... 0.62602404 0.86409814 0.69906169]
 ...
 [0.56173429 0.46738715 0.62602404 ... 0.         0.58791741 0.07307874]
 [0.60637964 0.3658476  0.86409814 ... 0.58791741 0.         0.58896508]
 [0.62658519 0.42282658 0.69906169 ... 0.07307874 0.58896508 0.        ]]


#### 28. Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) с заменой?

In [ ]:
array = np.arange(10, dtype=np.int32)
array = array.astype(np.float32, copy=False)
print(array)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 29. Создайте массив из следующего файла: (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
f = StringIO("""1, 2, 3, 4, 5\n
 6, , , 7, 8\n
 , , 9,10,11\n""")
array = np.genfromtxt(f, delimiter=",")
print(array)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 30. Вычтите среднее значение каждой строки случайной матрицы. (★★☆)

In [ ]:
array = np.random.random(size = (5, 3))
print(array)
array = array - array.mean(axis=1, keepdims=True)
print(array)

[[0.6657805  0.94196235 0.41357407]
 [0.03861099 0.43124219 0.50786658]
 [0.47070404 0.2298343  0.26008085]
 [0.5778657  0.4030962  0.19787334]
 [0.36880327 0.2150929  0.58833586]]
[[-0.00799181  0.26819004 -0.26019824]
 [-0.2872956   0.1053356   0.18195999]
 [ 0.15049764 -0.0903721  -0.06012555]
 [ 0.18492062  0.01015112 -0.19507174]
 [-0.02194074 -0.17565111  0.19759185]]


#### 31. Рассмотрим случайный вектор, как добавить 1 к каждому элементу, индексированному вторым вектором (будьте осторожны с повторяющимися индексами)? (★★★)

Без учета повторов

In [ ]:
array_1 = np.random.randint(10, size = 10)
print(array_1)
array_2 = np.unique(np.random.randint(len(array_1), size = 10))
print(array_2)
np.add.at(array_1, array_2, 1)
print(array_1)

[2 5 4 1 7 1 7 9 3 9]
[0 1 3 4 5 7]
[ 3  6  4  2  8  2  7 10  3  9]


Учитывая повторы

In [ ]:
array_1 = np.random.randint(10, size = 10)
print(array_1)
array_2 = np.random.randint(len(array_1), size = 10)
print(array_2)
np.add.at(array_1, array_2, 1)
print(array_1)

[7 7 1 9 8 3 5 1 3 6]
[3 6 0 0 2 7 1 3 8 8]
[ 9  8  2 11  8  3  6  2  5  6]


#### 32. Как перенести элементы вектора (X) в массив (F) на основе списка индексов (I)? (★★★)

In [ ]:
X = np.random.randint(10, size = 5)
print(X)
F = np.random.randint(10, size = 10)
print(F)
I = np.array([4, 3, 1, 0, 7])
print(I)
F[I] = X
print(F)

[0 9 1 2 8]
[4 1 6 4 8 3 2 8 9 5]
[4 3 1 0 7]
[2 1 6 9 0 3 2 8 9 5]


#### 33. Рассматривая четырехмерный массив, как получить сумму сразу (в одну операцию) по двум последним осям? (★★★)

In [ ]:
array = np.random.randint(10, size = (2, 2, 2, 2))
print(array)
print(np.sum(array, axis = (-2, -1)))

[[[[1 1]
   [7 1]]

  [[9 3]
   [8 4]]]


 [[[7 2]
   [9 5]]

  [[1 4]
   [2 7]]]]

[[10 24]
 [23 14]]


#### 34. Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением? (★★★)

In [ ]:
array = np.array([1, 2, 3, 4, 5])
n = 3
array_1 = np.zeros(len(array) + (len(array) - 1)*(n))
array_1[::n + 1] = array
print(array_1)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 35. Рассмотрим массив размерности (5,5,3), как его умножить на массив размерностью (5,5)? (★★★)

In [ ]:
array_1 = np.ones((5,5,3))
array_2 = 2*np.ones((5,5))
print(array_1 * array_2[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 36. Как вычислить средние значения, используя скользящее окно по массиву? (★★★)

In [ ]:
def moving_average(x, w):
  print(np.convolve(x, np.ones(w), "valid"))
  return np.convolve(x, np.ones(w), "valid") / w
array = np.arange(10)
print(moving_average(array, 3))

[0 1 2 3 4 5 6 7 8 9]
[ 3.  6.  9. 12. 15. 18. 21. 24.]


array([1., 2., 3., 4., 5., 6., 7., 8.])

#### 37. Рассмотрим одномерный массив Z, постройте из него двумерный массив, первая строка которого (Z[0],Z[1],Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть (Z[ -3],Z[-2],Z[-1]) (★★★)

In [ ]:
def rolling(a, window):
  shape = (a.size - window + 1, window)
  strides = (a.itemsize, a.itemsize)
  return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 38. Рассмотрим 2 набора точек P0,P1, описывающих линии (2d), и набор точек P. Как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])?(★★★)

In [ ]:
def distance(P0, P1, p):
    print(P0)
    print(P1)
    print(p)
    T = P1 - P0
    U = ((p[0] - P0[:, 0]) * T[:, 1] - T[:, 0] * (p[1] - P0[:, 1]))/ (T**2).sum(axis=1)
    U = U.reshape(len(U), 1)
    D = U * T
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.randint(5, size = (1,2))
P1 = np.random.randint(5, size = (1,2))
P = np.random.randint(1, size = (1,2))
print(np.array([distance(P0, P1, p_i) for p_i in P]))

[[0 3]]
[[3 1]]
[0 0]
[[2.49615088]]


#### 39. Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1, 15)
R = np.lib.stride_tricks.as_strided(Z, (len(Z) - 3, 4), Z.strides*2)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 ...
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 40. Найдите ранг случайной матрицы (★★★)

In [ ]:
array = np.random.randint(10, size = (3, 3))
print(array)
print(np.linalg.matrix_rank(array))

[[1 1 4]
 [8 6 7]
 [7 8 8]]
3


#### 41. Как найти наиболее часто встречающееся значение в массиве?

In [ ]:
array = np.random.randint(10, size = (3, 3))
print(array)
values, counts = np.unique(array.ravel(), return_counts=True)
print(values[np.argmax(counts)])

[[3 3 9]
 [7 6 9]
 [5 5 7]]
3


#### 42. Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B? (★★★)

In [ ]:
A = np.random.randint(10, size = (8, 3))
print(A)
B = np.random.randint(10, size = (2, 2))
print(B)

C = (A[..., np.newaxis, np.newaxis] == B)

rows = np.where(C.any((1, 3)).all(1))[0]
print(rows)

[[5 2 5]
 [8 1 3]
 [2 6 3]
 [3 9 8]
 [2 0 5]
 [2 3 9]
 [9 1 5]
 [3 9 4]]
[[0 9]
 [4 8]]
[3 7]


#### 43. Как извлечь уникальные значения из 2-х двумерных массивов?(★★★)

In [ ]:
A = np.random.randint(10, size = (2, 2))
B = np.random.randint(10, size = (2, 2))
print(np.unique(np.concatenate((A.ravel(), B.ravel()))))

[0 1 2 6 8 9]
